# Default values for reverser.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

name: reverser
environment: prod

service:
  type: ClusterIP
  port: 80

image:
  repository: europe-west1-docker.pkg.dev
  projectName: bamboo-copilot-407420
  registryName: prod-europe-west1-registry
  imgName: reverser
  pullPolicy: Always
  tag: latest
  exposePort: 9090

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
