apiVersion: v1
kind: Service
metadata:
  name: {{ include "namespaced_svcName" . }}-svc
spec:
  selector:
    app: {{ include "namespaced_svcName" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.exposePort }}
