# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

env:
  PROJECT_ID: bamboo-copilot-407420
  REGION: eu-west1
  GAR_LOCATION: europe-west1-docker.pkg.dev/bamboo-copilot-407420/prod-europe-west1-registry/reverser:latest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint
      run: golint ./...

  image-build:
    environment: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up gcloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Verify gcloud CLI"
        run: "gcloud info && gcloud components update"

      - name: "Docker registry auth"
        run: |-
          make auth-registry

      - name: Build image
        run: make docker-build IMG_TAG=${{ github.ref_name }}

      - name: Push image
        run: make docker-push IMG_TAG=${{ github.ref_name }}
